import { chromium } from "playwright";
import { mkdirSync } from "fs";
mkdirSync("/workspace/screenshots/qa", { recursive: true });
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 1800 } });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.getByRole("button", { name: "Antiqua", exact: true }).click();
await page.waitForTimeout(300);
const jump = page.getByLabel("Druckseite");
await jump.fill("667");
await jump.dispatchEvent("input");
await jump.dispatchEvent("change");
await page.waitForTimeout(800);
const article = page.locator("article.enc-page");
const label = await article.getAttribute("aria-label");
const tables = await article.locator("table").count();
const text = await article.innerText();
console.log("aria", label, "tables", tables, "has Berlin", text.includes("Berlin"), "has 4024286", text.includes("4024286"));
await article.screenshot({ path: "/workspace/screenshots/qa/recon-s667.png" });
await page.getByRole("button", { name: "Scan", exact: true }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/screenshots/qa/scan-s667.png", fullPage: true });
await page.getByRole("button", { name: "Synopse", exact: true }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/screenshots/qa/synopse-s667.png", fullPage: true });
console.log("ok");
await browser.close();
